## 2.1 Manipulação de Dados

In [1]:
%load_ext autoreload
%autoreload 2

%matplotlib inline

In [4]:
import torch

In [5]:
x = torch.arange(12) ; x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
x.shape

torch.Size([12])

In [8]:
x.size()

torch.Size([12])

### Mudar o formato sem alterar os valores ou a quantidade deles 

In [9]:
x.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Se não informarmos 1 dimensão e colocarmos `-1` em seu lugar, o Pytorch infere as demais.

In [10]:
x.reshape(3,-1)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [11]:
x.reshape(-1, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [13]:
x.reshape(-1, 2, 2)

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

In [18]:
torch.randn((3,4))

tensor([[-1.8263,  0.2680,  0.1158,  0.2596],
        [-1.5539,  0.6815, -1.7199, -0.6503],
        [-1.1129, -1.2627, -1.1812,  0.1253]])

Tensor Nulo

In [15]:
torch.zeros((3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Tensor Unitário

In [20]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

Amostragem de uma distribuição

In [30]:
x = torch.normal(0,1, (3,4))

In [31]:
x.mean()

tensor(0.0288)

In [32]:
x.std()

tensor(0.8946)

É possível criar um tensor fornecendo os valores exatos à partir de objetos python, como uma lista de listas

In [33]:
torch.Tensor([[2,1,4,3], [1,2,3,4], [4,3,2,1]])

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

A lista externa corresponde à dimensão 0, ou as linhas para 2 dimensões, e as listas internas correspondem à dimensão 1, ou colunas para 2 dimensões.

### Operações Elemento a Elemento

In [39]:
x = torch.Tensor([1,2,4,8])
y = torch.Tensor([2,2,2,2])

In [44]:
x+y, x-y, x*y, x**y # Exponencial

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([ 1.,  4., 16., 64.]))

Operação Unária - e.g. Exponenciação

In [46]:
torch.exp(x) 

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

Empilhar Tensores

In [53]:
x = torch.arange(12).reshape(3,4).float()
y = torch.Tensor([[2,1,4,3], [1,2,3,4], [4,3,2,1]]).float()
z = torch.stack([x,y], dim=0) ; z

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]])

In [54]:
z.shape

torch.Size([2, 3, 4])

In [55]:
z = torch.stack([x,y], dim=1) ; z

tensor([[[ 0.,  1.,  2.,  3.],
         [ 2.,  1.,  4.,  3.]],

        [[ 4.,  5.,  6.,  7.],
         [ 1.,  2.,  3.,  4.]],

        [[ 8.,  9., 10., 11.],
         [ 4.,  3.,  2.,  1.]]])

In [56]:
z.shape

torch.Size([3, 2, 4])

In [60]:
z = torch.stack([x,y], dim=2) ; z

tensor([[[ 0.,  2.],
         [ 1.,  1.],
         [ 2.,  4.],
         [ 3.,  3.]],

        [[ 4.,  1.],
         [ 5.,  2.],
         [ 6.,  3.],
         [ 7.,  4.]],

        [[ 8.,  4.],
         [ 9.,  3.],
         [10.,  2.],
         [11.,  1.]]])

In [58]:
z.shape

torch.Size([3, 4, 2])

### Criar tensores booleanos à partir de comparações

In [61]:
z = x == y ; z

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [62]:
z.sum()

tensor(2)

## Broadcasting


In [63]:
a = torch.arange(3).reshape(3,1)
b = torch.arange(2).reshape(1, 2)
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

Como as dimensões não casam se quisermos adicionar essas matrizes, nós _transmitimos_ os valores de ambas as matrizes numa matriz maior de tamanho `3x2`. Para a matriz `a` nós replicamos a coluna 1 vez, para a matriz b, nos replicamos as linhas 2 vezes.

In [64]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### Converter um escalar de tamanho 1 para um escalar em python

In [67]:
a = torch.Tensor([1.]) ; a

tensor([1.])

In [70]:
a.item()

1.0

In [71]:
float(a)

1.0

In [72]:
int(a)

1

### Multiplicação de Matrizes
Definição básica

In [84]:
def matmul(a,b):
    arows, acols = a.shape # n_rows * n_cols
    brows, bcols = b.shape
    assert acols==brows
    c = torch.zeros(arows, bcols)
    for i in range(arows):
        for j in range(bcols):
            for k in range(acols): # or br
                c[i,j] += a[i,k] * b[k,j]
    return c

In [77]:
x.shape

torch.Size([3, 4])

In [78]:
y.shape

torch.Size([3, 4])

In [81]:
y = y.reshape(4,3)

In [82]:
y.shape

torch.Size([4, 3])

In [85]:
%time t1=matmul(x, y)

CPU times: user 932 µs, sys: 127 µs, total: 1.06 ms
Wall time: 4.22 ms


Eliminando o índice `k`, usando a multiplicação elemento a elemento e o método `sum` do Tensor.

In [86]:
def matmul(a,b):
    arows, acols = a.shape # n_rows * n_cols
    brows, bcols = b.shape
    assert acols==brows
    c = torch.zeros(arows, bcols)
    for i in range(arows):
        for j in range(bcols):
            c[i,j] = (a[i,:] * b[:,j]).sum()
    return c

In [87]:
%time t1=matmul(x, y)

CPU times: user 629 µs, sys: 0 ns, total: 629 µs
Wall time: 643 µs


Você pode indexar com o valor especial [None] or usar `unsqueeze()`  para converter um tensor unidimensional em um vetor de 2 dimensões (A dimensão criada terá valor 1).

In [89]:
x.shape, x.unsqueeze(0).shape,x.unsqueeze(1).shape, x.unsqueeze(2).shape

(torch.Size([3, 4]),
 torch.Size([1, 3, 4]),
 torch.Size([3, 1, 4]),
 torch.Size([3, 4, 1]))

In [90]:
def matmul(a,b):
    arows, acols = a.shape # n_rows * n_cols
    brows, bcols = b.shape
    assert acols==brows
    c = torch.zeros(arows, bcols)
    for i in range(arows):
        c[i] = (a[i].unsqueeze(-1) * b).sum(dim=0)
    return c

In [91]:
%time t1=matmul(x, y)

CPU times: user 283 µs, sys: 40 µs, total: 323 µs
Wall time: 328 µs


Implementação do Pytorch

In [96]:
%time t1= x.matmul(y)

CPU times: user 128 µs, sys: 0 ns, total: 128 µs
Wall time: 133 µs


Equivalente

In [97]:
%time t1= x@y

CPU times: user 84 µs, sys: 13 µs, total: 97 µs
Wall time: 101 µs


Similar à norma $l_2$ para vetores, para matrizes a norma equivalente é a norma de Frobenius ( com a multiplicação de todos os valores da matriz dois a dois:
$\|\mathbf{X}\|_F = \sqrt{\sum_{i=1}^m \sum_{j=1}^n x_{ij}^2}.$

In [100]:
torch.norm(torch.ones(4,9))

tensor(6.)